tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/services"

# Essentials
brew "stow"
brew "git"
brew "shellcheck"

# Terminal
brew "spaceship"
cask "iterm2"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"

# Terminal tools
brew "zsh"
brew "httpie"
brew "jq"
brew "gh"
brew "eza"
brew "bat"
brew "make"
brew "diff-so-fancy"
brew "fzf"

# Docker
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "docker-machine"

# Languages
brew "golang"
brew "node"
brew "nvm"
brew "yarn"
brew "pyenv"

# Development apps
cask "visual-studio-code"
cask "firefox@developer-edition"
cask "google-chrome"
cask "beekeeper-studio"
cask "figma"
cask "postman"

# Productivity apps
cask "cron"
cask "notion"
cask "spotify"

# Communication apps
cask "zoom"
cask "slack"

# Utilities apps
cask "rectangle"
cask "logi-options-plus"
