name: Check code health

on:
  push:
    branches: [master, main]

  schedule:
    - cron: "0 9 * 1-12 6"

jobs:
  Scan:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan the repository to find hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  Shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Run Shellcheck
        run: make check-scripts

  Test:
    name: Test install and uninstall on macOS
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: Set up Homebrew PATH environment
        run: echo "/usr/local/bin:/usr/bin:/bin" >> "${GITHUB_PATH}"

      - name: Run install script
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/YasminTeles/dotfiles/main/install.sh)"
        env:
          CI: true

      - name: Show the Home directory
        run: |
            cd ~
            ls -la

      - name: Run uninstall script
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/YasminTeles/dotfiles/main/uninstall.sh)"
        env:
          CI: true

      - name: Show the Home directory
        run: |
            cd ~
            ls -la

  Message:
    name: Error message
    needs: [Scan, Shellcheck, Test]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: ":eyes: *${{ github.repository }}* GitHub Actions: ${{ github.workflow }} #${{ github.run_number }} failed.\n<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}|${{ github.event.head_commit.message }}>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
