name: Check code health

on:
  push:
    branches: [master, main]

jobs:
  Scan:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan the repository to find hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
